repos:
  - repo: local
    hooks:
      - id: poetry-export
        name: Export Poetry Requirements
        entry: powershell.exe -File export-requirements.ps1
        language: system
        files: ^pyproject\.toml$
        stages: [commit]
